---
title: "Untitled"
author: "Danai"
date: "2023-07-10"
output: html_document
---


```{r setup, include=FALSE}
library(readxl)
library(ggplot2)
library(zoo)
library(tidyverse)
library(here)
```


```{r data, include=FALSE}
data <- read_excel(here("isotope_data_results.xlsx"), sheet = "arch_FA") %>% 
  separate('SEAFRONT sample names',sep="_",into = c("trench","unit","specimen"),remove = FALSE) %>% 
  mutate(Chronology= factor(data$Chronology,
                          levels = c("FP", "LM", "UM", "FM", "FM/IN", "IN", "EN", "EN-MN", "MN", "LN", "FN"))) # I moved this line about factor order to here

# I DON"T UNDERSTAND THESE DATES BUT THEY NEED TO BE INTEGRATED I THINK?
range_start <- c(11700, 10800, 10291, 9500, 8900, 8600, 8499, 8300, 7500, 7300, 6100) 
range_end <- c(1400, 10300, 9501, 8601, 8500, 8500, 8000, 7700, 7301, 6600, 5700)


# data$cal_BP_start <- range_start
# data$cal_BP_end <- range_end


#### Your best friend put in some comments into this code:

# This script is used to process a dataset (`data`) for the purpose of adjusting
# or "stretching" the time information associated with archaeological trench 
# and unit data based on established chronologies.

# Start a chain of operations on `data` using the pipe operator (`%>%`)
data_stretch <- data %>% 

  # Group the data by `trench` and `Chronology` columns
  group_by(trench, Chronology) %>%

  # Create a new column `approx_time`. 
  # If `unit` is equal to the maximum `unit` in the group, assign `cal_BP_start` to `approx_time`.
  # Otherwise, assign `NA` to `approx_time`.
  mutate(approx_time = ifelse(unit == max(unit), cal_BP_start, NA),

  # Update `approx_time`. 
  # If `unit` is equal to the minimum `unit` in the group, assign `cal_BP_end` to `approx_time`.
  # Otherwise, leave `approx_time` unchanged.
         approx_time = ifelse(unit==min(unit),cal_BP_end,approx_time),

  # Update `approx_time` to replace `NA` values with an approximation based on linear interpolation
  # (or the closest non-`NA` value if interpolation is not possible).
         approx_time = na.approx(approx_time)) %>%

  # "Ungroup" the data to remove the grouping by `trench` and `Chronology`
  ungroup() %>% 

  # Group the data by `trench` and `unit`
  group_by(trench,unit) %>% 

  # Update `approx_time` to be the mean `approx_time` in the group
  mutate(approx_time=mean(approx_time),

  # Round `approx_time` to the nearest integer
         approx_time = round(approx_time,0)) %>% 

  # "Ungroup" the data to remove the grouping by `trench` and `unit`
  ungroup() %>% 

  # Arrange the data in ascending order by `trench` and `unit`
  arrange(trench,unit)

####

plot <-
  ggplot(data_stretch, aes(x = approx_time, y =d18O , color = Season)) +
  geom_linerange(aes(ymin = d18O - internal, ymax = d18O + internal)) +
  geom_point() +
  stat_smooth(data = subset(data_stretch, Season == "Winter"), aes(group = Season), method = "loess", se = TRUE, span = 0.5) +
  stat_smooth(data = subset(data_stretch, Season == "Summer"), aes(group = Season), method = "loess", se = TRUE, span = 0.5) +
  labs(x = "Chronology", y = bquote(delta ^ 18 * O ~ "(‰ VPDB)"), color = "Season",
       title = expression(paste("Changes in ", delta ^ 18 * O, " in Franchthi cave"))) +
  theme_minimal() +
  scale_y_reverse() +
  scale_x_reverse() +  # Reverse the x-axis
  theme(plot.title = element_text(hjust = 0.5))

plot

# print(plot)

# ggsave("plot.png", plot, width = 8, height = 6, dpi = 300)


```
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
